apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudnative-config
  namespace: cloudnative
data:
  DB_HOST: "cloudnativedb-service"
  DB_PORT: "5432"
  DB_USER: "cloudnativeuser"
  DB_NAME: "cloudnativedb"

  POSTGRES_DB: "cloudnativedb"
  POSTGRES_USER: "cloudnativeuser"

  AUTH_PORT: "8080"
  FILE_PORT: "8081"
---

