apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-secrets
  namespace: cloudnative
type: Opaque
data:
  JWT_SECRET: Y2xvdWRuYXRpdmUtZGV2LWp3dC1zZWNyZXQtY2hhbmdlLW1l
  DB_PASSWORD: Y2xvdWRuYXRpdmVwYXNzd29yZA==
---

